#!/bin/bash

gatewayIP=`ip route | awk {'print $3'} | head -n1`
LOG=/home/pi/temp.log


ping -c4 $gatewayIP > /dev/null

if [ $? -gt 0 ]; then
	echo [`date '+%c'`]: Wifi lost, trying to bring up >> $LOG
	/sbin/ifup --force wlan0
	
	sleep 5
	ping -c4 $gatewayIP > /dev/null
	if [ $? -gt 0 ]; then
    	echo [`date '+%c'`]: Wifi still down, trying to bring up >> $LOG
		/sbin/iffown wlan0
	    	/sbin/ifup --force wlan0
		
		sleep 5
		ping -c4 $gatewayIP > /dev/null
		if [ $? -gt 0 ]; then
    		echo [`date '+%c'`]: Wifi still down, rebooting >> $LOG
			/sbin/reboot
		fi
	fi
fi

exit 0
